services:
  - type: web
    name: ree-final
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt && alembic upgrade head
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: RUNPOD_ENDPOINT_URL
        value: https://w5abq0pu3s478s-11434.proxy.runpod.net/v1
      - key: RUNPOD_CHAT_MODEL
        value: qwen2.5:14b
      - key: RUNPOD_EMBEDDING_MODEL
        value: nomic-embed-text
      - key: STORAGE_DIR
        value: ./storage
      - key: GAP_THRESHOLD_MONTHS
        value: "6"


