"""initial schema

Revision ID: 00788d4a54e0
Revises: 
Create Date: 2026-08-17 12:09:52.175019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00788d4a54e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=400), nullable=False),
    sa.Column('pdf_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'EXTRACTED', 'INDEXED', 'SKILLS_IDENTIFIED', 'WAITING_FOR_SKILL_VERIFICATION', 'SKILLS_VERIFIED', 'EVALUATING', 'COMPLETED', 'PARTIAL', 'FAILED', name='resumestatus', native_enum=False, length=40), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('failed_stage', sa.String(length=60), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_pdf_hash'), 'resumes', ['pdf_hash'], unique=False)
    op.create_table('role_domains',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role_levels',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('rank')
    )
    op.create_table('technical_skill_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('resume_evaluations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('resume_id', sa.String(length=36), nullable=False),
    sa.Column('pdf_hash', sa.String(length=64), nullable=False),
    sa.Column('verified_skill_set_hash', sa.String(length=64), nullable=False),
    sa.Column('completeness_score', sa.Float(), nullable=False),
    sa.Column('growth_score', sa.Float(), nullable=False),
    sa.Column('evidence_score', sa.Float(), nullable=False),
    sa.Column('experience_score', sa.Float(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'PARTIAL', 'FAILED', name='evaluationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('failed_components', sa.JSON(), nullable=False),
    sa.Column('overall_assessment', sa.Text(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('weaknesses', sa.JSON(), nullable=False),
    sa.Column('key_risks', sa.JSON(), nullable=False),
    sa.Column('interview_preparation', sa.JSON(), nullable=False),
    sa.Column('telemetry', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('embedding_version', sa.String(length=50), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('skill_taxonomy_version', sa.String(length=50), nullable=False),
    sa.Column('role_taxonomy_version', sa.String(length=50), nullable=False),
    sa.Column('normalization_version', sa.String(length=50), nullable=False),
    sa.Column('agent_version', sa.String(length=50), nullable=False),
    sa.Column('scoring_version', sa.String(length=50), nullable=False),
    sa.Column('chunking_version', sa.String(length=50), nullable=False),
    sa.Column('vector_index_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_evaluations_pdf_hash'), 'resume_evaluations', ['pdf_hash'], unique=False)
    op.create_index(op.f('ix_resume_evaluations_resume_id'), 'resume_evaluations', ['resume_id'], unique=False)
    op.create_table('resume_extractions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resume_id', sa.String(length=36), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=False),
    sa.Column('blocks', sa.JSON(), nullable=False),
    sa.Column('reading_order', sa.JSON(), nullable=False),
    sa.Column('extraction_version', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_extractions_resume_id'), 'resume_extractions', ['resume_id'], unique=False)
    op.create_table('resume_gaps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resume_id', sa.String(length=36), nullable=False),
    sa.Column('gap_start', sa.Date(), nullable=False),
    sa.Column('gap_end', sa.Date(), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_gaps_resume_id'), 'resume_gaps', ['resume_id'], unique=False)
    op.create_table('resume_sections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resume_id', sa.String(length=36), nullable=False),
    sa.Column('canonical_section', sa.Enum('CONTACT', 'SUMMARY', 'SKILLS', 'EXPERIENCE', 'PROJECTS', 'EDUCATION', 'CERTIFICATIONS', 'ACHIEVEMENTS', 'AWARDS', 'PUBLICATIONS', 'INTERESTS', 'OTHER', name='canonicalsection', native_enum=False, length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('block_ids', sa.JSON(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_sections_resume_id'), 'resume_sections', ['resume_id'], unique=False)
    op.create_table('roles',
    sa.Column('role_id', sa.String(length=100), nullable=False),
    sa.Column('canonical_title', sa.String(length=150), nullable=False),
    sa.Column('normalized_title', sa.String(length=150), nullable=False),
    sa.Column('role_family', sa.String(length=100), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('seniority_level_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('vector_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['role_domains.id'], ),
    sa.ForeignKeyConstraint(['seniority_level_id'], ['role_levels.id'], ),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_index(op.f('ix_roles_canonical_title'), 'roles', ['canonical_title'], unique=True)
    op.create_index(op.f('ix_roles_normalized_title'), 'roles', ['normalized_title'], unique=False)
    op.create_table('technical_skills',
    sa.Column('skill_id', sa.String(length=80), nullable=False),
    sa.Column('canonical_name', sa.String(length=150), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('skill_type', sa.String(length=50), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('parent_skill_id', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deprecated', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('vector_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['technical_skill_categories.id'], ),
    sa.ForeignKeyConstraint(['parent_skill_id'], ['technical_skills.skill_id'], ),
    sa.PrimaryKeyConstraint('skill_id')
    )
    op.create_index(op.f('ix_technical_skills_canonical_name'), 'technical_skills', ['canonical_name'], unique=True)
    op.create_table('resume_agent_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resume_id', sa.String(length=36), nullable=False),
    sa.Column('evaluation_id', sa.String(length=36), nullable=True),
    sa.Column('agent_name', sa.String(length=60), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'PARTIAL', 'FAILED', 'SKIPPED', name='agentrunstatus', native_enum=False, length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('qwen_calls', sa.Integer(), nullable=False),
    sa.Column('telemetry', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['evaluation_id'], ['resume_evaluations.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_agent_runs_resume_id'), 'resume_agent_runs', ['resume_id'], unique=False)
    op.create_table('resume_chunks',
    sa.Column('chunk_id', sa.String(length=36), nullable=False),
    sa.Column('resume_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_type', sa.Enum('SUMMARY', 'CONTACT', 'SKILL_SECTION', 'EXPERIENCE_ROLE', 'EXPERIENCE_RESPONSIBILITY', 'EXPERIENCE_TECHNOLOGY', 'EXPERIENCE_PROJECT', 'PROJECT', 'EDUCATION', 'CERTIFICATION', 'ACHIEVEMENT', 'PUBLICATION', 'OTHER', name='chunktype', native_enum=False, length=30), nullable=False),
    sa.Column('section', sa.Enum('CONTACT', 'SUMMARY', 'SKILLS', 'EXPERIENCE', 'PROJECTS', 'EDUCATION', 'CERTIFICATIONS', 'ACHIEVEMENTS', 'AWARDS', 'PUBLICATIONS', 'INTERESTS', 'OTHER', name='canonicalsection', native_enum=False, length=20), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('role_raw', sa.String(length=200), nullable=True),
    sa.Column('role_canonical_id', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('parent_chunk_id', sa.String(length=36), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('embedding_text', sa.Text(), nullable=False),
    sa.Column('vector_id', sa.Integer(), nullable=True),
    sa.Column('embedding_model', sa.String(length=60), nullable=True),
    sa.Column('embedding_version', sa.String(length=30), nullable=True),
    sa.Column('embedding_dimension', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_chunk_id'], ['resume_chunks.chunk_id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.ForeignKeyConstraint(['role_canonical_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_index(op.f('ix_resume_chunks_resume_id'), 'resume_chunks', ['resume_id'], unique=False)
    op.create_index(op.f('ix_resume_chunks_vector_id'), 'resume_chunks', ['vector_id'], unique=False)
    op.create_table('resume_evaluation_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evaluation_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.Enum('COMPLETENESS', 'GROWTH', 'EVIDENCE', 'EXPERIENCE', name='scorecategory', native_enum=False, length=20), nullable=False),
    sa.Column('sub_dimension', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=30), nullable=True),
    sa.Column('points_awarded', sa.Float(), nullable=False),
    sa.Column('points_max', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('source_chunk_ids', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['resume_evaluations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_evaluation_scores_evaluation_id'), 'resume_evaluation_scores', ['evaluation_id'], unique=False)
    op.create_table('resume_experiences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('resume_id', sa.String(length=36), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('raw_title', sa.String(length=200), nullable=False),
    sa.Column('canonical_role_id', sa.String(length=100), nullable=True),
    sa.Column('canonical_title', sa.String(length=200), nullable=True),
    sa.Column('role_family', sa.String(length=100), nullable=True),
    sa.Column('seniority_level_id', sa.Integer(), nullable=True),
    sa.Column('seniority_ambiguous', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('responsibilities', sa.JSON(), nullable=False),
    sa.Column('technologies', sa.JSON(), nullable=False),
    sa.Column('projects', sa.JSON(), nullable=False),
    sa.Column('leadership_indicators', sa.JSON(), nullable=False),
    sa.Column('ownership_indicators', sa.JSON(), nullable=False),
    sa.Column('responsibility_level', sa.String(length=40), nullable=True),
    sa.Column('source_chunk_ids', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['canonical_role_id'], ['roles.role_id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.ForeignKeyConstraint(['seniority_level_id'], ['role_levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_experiences_resume_id'), 'resume_experiences', ['resume_id'], unique=False)
    op.create_table('resume_recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evaluation_id', sa.String(length=36), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('audience', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['resume_evaluations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_recommendations_evaluation_id'), 'resume_recommendations', ['evaluation_id'], unique=False)
    op.create_table('resume_skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('resume_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=80), nullable=False),
    sa.Column('detected_text', sa.String(length=150), nullable=False),
    sa.Column('canonical_name', sa.String(length=150), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('detection_method', sa.Enum('EXACT', 'ALIAS', 'FUZZY', 'SEMANTIC', 'QWEN_VALIDATED', name='detectionmethod', native_enum=False, length=20), nullable=False),
    sa.Column('verification_status', sa.Enum('AUTO_CONFIRMED', 'USER_CONFIRMED', 'USER_CORRECTED', 'USER_REMOVED', name='verificationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('source_chunk_ids', sa.JSON(), nullable=False),
    sa.Column('user_modified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['technical_skills.skill_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_skills_resume_id'), 'resume_skills', ['resume_id'], unique=False)
    op.create_index(op.f('ix_resume_skills_skill_id'), 'resume_skills', ['skill_id'], unique=False)
    op.create_table('role_aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.String(length=100), nullable=False),
    sa.Column('alias_text', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_aliases_alias_text'), 'role_aliases', ['alias_text'], unique=False)
    op.create_index(op.f('ix_role_aliases_role_id'), 'role_aliases', ['role_id'], unique=False)
    op.create_table('role_skill_relations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.String(length=100), nullable=False),
    sa.Column('skill_id', sa.String(length=80), nullable=False),
    sa.Column('relation_type', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['technical_skills.skill_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_skill_relations_role_id'), 'role_skill_relations', ['role_id'], unique=False)
    op.create_index(op.f('ix_role_skill_relations_skill_id'), 'role_skill_relations', ['skill_id'], unique=False)
    op.create_table('technical_skill_aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('skill_id', sa.String(length=80), nullable=False),
    sa.Column('alias_text', sa.String(length=150), nullable=False),
    sa.Column('alias_type', sa.Enum('ALIAS', 'ABBREVIATION', 'MISSPELLING', name='skillaliastype', native_enum=False, length=20), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['technical_skills.skill_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technical_skill_aliases_alias_text'), 'technical_skill_aliases', ['alias_text'], unique=False)
    op.create_index(op.f('ix_technical_skill_aliases_skill_id'), 'technical_skill_aliases', ['skill_id'], unique=False)
    op.create_table('technical_skill_relations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('skill_id', sa.String(length=80), nullable=False),
    sa.Column('related_skill_id', sa.String(length=80), nullable=False),
    sa.Column('relation_type', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['related_skill_id'], ['technical_skills.skill_id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['technical_skills.skill_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technical_skill_relations_skill_id'), 'technical_skill_relations', ['skill_id'], unique=False)
    op.create_table('resume_skill_evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resume_skill_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_type', sa.Enum('EXPLICIT_IMPLEMENTATION', 'PROJECT_USAGE', 'RESPONSIBILITY_USAGE', 'TECHNICAL_ENVIRONMENT', 'CERTIFICATION_ONLY', 'SKILLS_SECTION_ONLY', 'INFERRED', 'NONE', name='evidencetype', native_enum=False, length=30), nullable=False),
    sa.Column('evidence_strength', sa.Enum('STRONG', 'MODERATE', 'WEAK', 'NONE', name='evidencestrength', native_enum=False, length=10), nullable=False),
    sa.Column('qwen_explanation', sa.Text(), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['resume_chunks.chunk_id'], ),
    sa.ForeignKeyConstraint(['resume_skill_id'], ['resume_skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_skill_evidence_resume_skill_id'), 'resume_skill_evidence', ['resume_skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_skill_evidence_resume_skill_id'), table_name='resume_skill_evidence')
    op.drop_table('resume_skill_evidence')
    op.drop_index(op.f('ix_technical_skill_relations_skill_id'), table_name='technical_skill_relations')
    op.drop_table('technical_skill_relations')
    op.drop_index(op.f('ix_technical_skill_aliases_skill_id'), table_name='technical_skill_aliases')
    op.drop_index(op.f('ix_technical_skill_aliases_alias_text'), table_name='technical_skill_aliases')
    op.drop_table('technical_skill_aliases')
    op.drop_index(op.f('ix_role_skill_relations_skill_id'), table_name='role_skill_relations')
    op.drop_index(op.f('ix_role_skill_relations_role_id'), table_name='role_skill_relations')
    op.drop_table('role_skill_relations')
    op.drop_index(op.f('ix_role_aliases_role_id'), table_name='role_aliases')
    op.drop_index(op.f('ix_role_aliases_alias_text'), table_name='role_aliases')
    op.drop_table('role_aliases')
    op.drop_index(op.f('ix_resume_skills_skill_id'), table_name='resume_skills')
    op.drop_index(op.f('ix_resume_skills_resume_id'), table_name='resume_skills')
    op.drop_table('resume_skills')
    op.drop_index(op.f('ix_resume_recommendations_evaluation_id'), table_name='resume_recommendations')
    op.drop_table('resume_recommendations')
    op.drop_index(op.f('ix_resume_experiences_resume_id'), table_name='resume_experiences')
    op.drop_table('resume_experiences')
    op.drop_index(op.f('ix_resume_evaluation_scores_evaluation_id'), table_name='resume_evaluation_scores')
    op.drop_table('resume_evaluation_scores')
    op.drop_index(op.f('ix_resume_chunks_vector_id'), table_name='resume_chunks')
    op.drop_index(op.f('ix_resume_chunks_resume_id'), table_name='resume_chunks')
    op.drop_table('resume_chunks')
    op.drop_index(op.f('ix_resume_agent_runs_resume_id'), table_name='resume_agent_runs')
    op.drop_table('resume_agent_runs')
    op.drop_index(op.f('ix_technical_skills_canonical_name'), table_name='technical_skills')
    op.drop_table('technical_skills')
    op.drop_index(op.f('ix_roles_normalized_title'), table_name='roles')
    op.drop_index(op.f('ix_roles_canonical_title'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_resume_sections_resume_id'), table_name='resume_sections')
    op.drop_table('resume_sections')
    op.drop_index(op.f('ix_resume_gaps_resume_id'), table_name='resume_gaps')
    op.drop_table('resume_gaps')
    op.drop_index(op.f('ix_resume_extractions_resume_id'), table_name='resume_extractions')
    op.drop_table('resume_extractions')
    op.drop_index(op.f('ix_resume_evaluations_resume_id'), table_name='resume_evaluations')
    op.drop_index(op.f('ix_resume_evaluations_pdf_hash'), table_name='resume_evaluations')
    op.drop_table('resume_evaluations')
    op.drop_table('technical_skill_categories')
    op.drop_table('role_levels')
    op.drop_table('role_domains')
    op.drop_index(op.f('ix_resumes_pdf_hash'), table_name='resumes')
    op.drop_table('resumes')
    # ### end Alembic commands ###
